### ISSUE TITLE
18.01.2022

### ISSUE THREAD

**Issue by Rovshen98** [Aysel552/PragmatechFrontEndProject#1]
Son 10 gündə repo update olunmayıb

**Comment by Aysel552** [comment]
Salam,
zehmet olmasa FirstWebProject yoxlayin.Men beshinci gun ora push etmishem

Aysel Abbasaliyeva
Data Analyst | Information Management | SAP |
SAS Analyst | Social Network Analyst Gephi |
Business Intelligence
NOVA IMS Information management school
Lisbon, Lisbon, Portugal
*https://www.linkedin.com/in/aysel-data-analyst/
<https://www.linkedin.com/in/aysel-data-analyst/>*

**Comment by Aysel552** [comment]
Neyise duz etmiremse,zehmet olmasa komek edin.

Aysel Abbasaliyeva
Data Analyst | Information Management | SAP |
SAS Analyst | Social Network Analyst Gephi |
Business Intelligence
NOVA IMS Information management school
Lisbon, Lisbon, Portugal
*https://www.linkedin.com/in/aysel-data-analyst/
<https://www.linkedin.com/in/aysel-data-analyst/>*
